
postgres:
    image: postgres
    ports:
        - "5432" # random available host port will be chosen, same as -P

    environment:
        - e=mypass
        # you can also set the postgres username and database name

dbservice:
    build: ./dbservice
    links:
        - postgres:db # [other container]:[alias in this container]
        # this will create environment variables in the go container
        # with ip and port info for the postgres container
        # also creates entries in /etc/hosts with ip info
    ports:
        - "3000:8080" # this is port i'm exposing in the container

